
store_backend_category_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:Category:list }


store_backend_category_view:
    path:     /view/{id}/{name}
    defaults: { _controller: StoreBackendBundle:Category:view }
    requirements:
     id: \d+  #on ne veut que les nombre numberic
     _method: GET   #on ne veut que le GET


store_backend_category_remove:
    path:     /remove/{id}
    defaults: { _controller: StoreBackendBundle:Category:remove }
